name: clang

on:
  push:
    branches:
    - main
    - feature/*
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
    - '**.md'
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Xcode
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Verify Clang version
      run: clang++ --version

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}} -j 3

    - name: Test
      working-directory: build
      run: ctest -C ${{env.BUILD_TYPE}} -j 3 --output-on-failure
